# .github/release-drafter.yml

name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
no-changes-template: "- No changes in this release."
contributors-template: "- @$CONTRIBUTOR"
sort-by: merged_at
sort-direction: descending
template: |
  ## Release Overview
  - Version: v$RESOLVED_VERSION
  - Comparison: [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)

  ## Changes by Category
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

categories:
  - title: "Breaking Changes"
    labels:
      - breaking-change
      - breaking

  - title: "Features"
    labels:
      - enhancement
      - feature
      - feat

  - title: "Bug Fixes"
    labels:
      - bug
      - fix

  - title: "Improvements"
    labels:
      - perf
      - refactor
      - style

  - title: "Maintenance & Documentation"
    labels:
      - build
      - chore
      - ci
      - dependencies
      - docs
      - test

exclude-labels:
  - ignore-for-release

exclude-contributors:
  - dependabot[bot]
  - renovate-bot
