# .github/workflows/auto-release.yml

name: Auto release on tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
